In [1]:
import pandas as pd
import numpy as np

In [18]:
from IPython.display import display
pd.options.display.max_columns = None

,date,state,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,onVentilatorCumulative,recovered,hash,dateChecked,death,hospitalized,total,totalTestResults,posNeg,fips,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease
0,20200404,AK,171.0,5869.0,NaN,NaN,16.0,NaN,NaN,NaN,NaN,NaN,10a0cf7d2d88dce27674dda730950a2661caa4b0,2020-04-04T20:00:00Z,5.0,16.0,6040,6040,6040,2,2.0,1.0,10.0,14.0,24.0
1,20200404,AL,1580.0,9273.0,NaN,NaN,212.0,NaN,NaN,NaN,NaN,NaN,963802ea3a71c8b5d74fec7b17f1fb98e9547168,2020-04-04T20:00:00Z,43.0,212.0,10853,10853,10853,1,8.0,212.0,1086.0,148.0,1234.0
2,20200404,AR,743.0,9627.0,NaN,72.0,NaN,NaN,NaN,23.0,NaN,79.0,b8737741e743a45a91088157640ca1a0b49adc9d,2020-04-04T20:00:00Z,14.0,NaN,10370,10370,10370,5,2.0,0.0,632.0,39.0,671.0
3,20200404,AS,NaN,20.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a7a8c57370e5f59f49e7b95394059c629156c29d,2020-04-04T20:00:00Z,0.0,NaN,26,20,20,60,0.0,0.0,0.0,0.0,0.0
4,20200404,AZ,2019.0,25141.0,NaN,NaN,297.0,NaN,104.0,NaN,NaN,NaN,cfb482b3a35b4fc17924cec3a44f93a4ca0644ad,2020-04-04T20:00:00Z,52.0,297.0,27160,27160,27160,4,11.0,48.0,2237.0,250.0,2487.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1648,20200304,OR,3.0,29.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d63f4cf486a6d2f86062b9af1bd46955abd90cb9,2020-03-04T21:00:00Z,NaN,NaN,50,32,32,41,NaN,NaN,NaN,NaN,NaN
1649,20200304,SC,0.0,5.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,012fa30a9958580f589eb7d1de5e5a81c327b1a5,2020-03-04T21:00:00Z,NaN,NaN,5,5,5,45,NaN,NaN,NaN,NaN,NaN
1650,20200304,TX,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d29839e81cae6ba53df2d1a1d7bfeddfd4fc8509,2020-03-04T21:00:00Z,NaN,NaN,1,1,1,48,NaN,NaN,NaN,NaN,NaN
1651,20200304,WA,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,e07bd12171fed21351784c462b0dab23d8cfabbd,2020-03-04T21:00:00Z,10.0,NaN,39,39,39,53,NaN,NaN,NaN,NaN,NaN
1652,20200304,WI,1.0,19.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,c1fede94be9a426dc9c3b5d26d33b9f168fec21c,2020-03-04T21:00:00Z,NaN,NaN,26,20,20,55,NaN,NaN,NaN,NaN,NaN

# Get Data

In [3]:
df = pd.read_csv("states-daily.csv")

In [19]:
df.head()

,date,state,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,onVentilatorCumulative,recovered,hash,dateChecked,death,hospitalized,total,totalTestResults,posNeg,fips,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease
0,20200404,AK,171.0,5869.0,NaN,NaN,16.0,NaN,NaN,NaN,NaN,NaN,10a0cf7d2d88dce27674dda730950a2661caa4b0,2020-04-04T20:00:00Z,5.0,16.0,6040,6040,6040,2,2.0,1.0,10.0,14.0,24.0
1,20200404,AL,1580.0,9273.0,NaN,NaN,212.0,NaN,NaN,NaN,NaN,NaN,963802ea3a71c8b5d74fec7b17f1fb98e9547168,2020-04-04T20:00:00Z,43.0,212.0,10853,10853,10853,1,8.0,212.0,1086.0,148.0,1234.0
2,20200404,AR,743.0,9627.0,NaN,72.0,NaN,NaN,NaN,23.0,NaN,79.0,b8737741e743a45a91088157640ca1a0b49adc9d,2020-04-04T20:00:00Z,14.0,NaN,10370,10370,10370,5,2.0,0.0,632.0,39.0,671.0
3,20200404,AS,NaN,20.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a7a8c57370e5f59f49e7b95394059c629156c29d,2020-04-04T20:00:00Z,0.0,NaN,26,20,20,60,0.0,0.0,0.0,0.0,0.0
4,20200404,AZ,2019.0,25141.0,NaN,NaN,297.0,NaN,104.0,NaN,NaN,NaN,cfb482b3a35b4fc17924cec3a44f93a4ca0644ad,2020-04-04T20:00:00Z,52.0,297.0,27160,27160,27160,4,11.0,48.0,2237.0,250.0,2487.0

In [13]:
df.columns

Index(['date', 'state', 'positive', 'negative', 'pending',
       'hospitalizedCurrently', 'hospitalizedCumulative', 'inIcuCurrently',
       'inIcuCumulative', 'onVentilatorCurrently', 'onVentilatorCumulative',
       'recovered', 'hash', 'dateChecked', 'death', 'hospitalized', 'total',
       'totalTestResults', 'posNeg', 'fips', 'deathIncrease',
       'hospitalizedIncrease', 'negativeIncrease', 'positiveIncrease',
       'totalTestResultsIncrease'],
      dtype='object')

In [20]:
df.isna().sum()

date                           0
state                          0
positive                       8
negative                     146
pending                     1186
hospitalizedCurrently       1538
hospitalizedCumulative      1192
inIcuCurrently              1618
inIcuCumulative             1583
onVentilatorCurrently       1620
onVentilatorCumulative      1610
recovered                   1503
hash                           0
dateChecked                    0
death                        681
hospitalized                1192
total                          0
totalTestResults               0
posNeg                         0
fips                           0
deathIncrease                 56
hospitalizedIncrease          56
negativeIncrease              56
positiveIncrease              56
totalTestResultsIncrease      56
dtype: int64

In [30]:
df["date"][0]

20200404

In [28]:
from datetime import datetime, timedelta

In [33]:
import copy
from copy import deepcopy

In [48]:
df["date"] = pd.to_datetime(df["date"], format = '%Y%m%d', errors = 'coerce')

In [59]:
df[df["state"] == "NY"]

,date,state,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,onVentilatorCumulative,recovered,hash,dateChecked,death,hospitalized,total,totalTestResults,posNeg,fips,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease
37,2020-04-04,NY,113704.0,169917.0,NaN,15905.0,26383.0,4126.0,NaN,NaN,NaN,10478.0,792799b4ed7e06f7995dec04e454a37ec5edb0c0,2020-04-04T20:00:00Z,3565.0,26383.0,283621,283621,283621,36,630.0,2687.0,12260.0,10841.0,23101.0
93,2020-04-03,NY,102863.0,157657.0,NaN,14810.0,23696.0,3731.0,NaN,NaN,NaN,8886.0,3581ea3846e784ce3996c873effe694f50617310,2020-04-03T20:00:00Z,2935.0,23696.0,260520,260520,260520,36,562.0,2879.0,11073.0,10482.0,21555.0
149,2020-04-02,NY,92381.0,146584.0,NaN,13383.0,20817.0,3396.0,NaN,NaN,NaN,7434.0,764d0566c27be04c416c502640d5fffbcb8cad26,2020-04-02T20:00:00Z,2373.0,20817.0,238965,238965,238965,36,432.0,2449.0,9416.0,8669.0,18085.0
205,2020-04-01,NY,83712.0,137168.0,NaN,12226.0,18368.0,3022.0,3022.0,NaN,NaN,6142.0,bc022c8f01dbc1a4d1f046ebce21c18a7b42cfa6,2020-04-01T20:00:00Z,1941.0,18368.0,220880,220880,220880,36,391.0,2464.0,7777.0,7917.0,15694.0
261,2020-03-31,NY,75795.0,129391.0,NaN,10929.0,15904.0,2710.0,2710.0,NaN,NaN,4975.0,a3afdea93fae4daf8073978749d736d46e9134c6,2020-03-31T20:00:00Z,1550.0,15904.0,205186,205186,205186,36,332.0,2183.0,9420.0,9298.0,18718.0
317,2020-03-30,NY,66497.0,119971.0,NaN,9517.0,13721.0,2352.0,2352.0,NaN,NaN,4204.0,a749060bc47c2573b505c13198673b348ed3cc2b,2020-03-30T20:00:00Z,1218.0,13721.0,186468,186468,186468,36,253.0,1646.0,7124.0,6984.0,14108.0
373,2020-03-29,NY,59513.0,112847.0,NaN,8503.0,12075.0,2037.0,2037.0,NaN,NaN,3572.0,b5656122e28105ae4788a0d68eabb1ef68a06287,2020-03-29T20:00:00Z,965.0,12075.0,172360,172360,172360,36,237.0,2021.0,9231.0,7195.0,16426.0
429,2020-03-28,NY,52318.0,103616.0,NaN,7328.0,10054.0,1755.0,1755.0,NaN,NaN,2726.0,7592db95575a5d4ef226ff6014283d8d85a0db52,2020-03-28T20:00:00Z,728.0,10054.0,155934,155934,155934,36,209.0,1528.0,2498.0,7683.0,10181.0
485,2020-03-27,NY,44635.0,101118.0,NaN,6481.0,8526.0,1583.0,1583.0,NaN,NaN,2045.0,d7f2dd3fcfbabebfdaeaa0a19e5db38d94fb112a,2020-03-27T20:00:00Z,519.0,8526.0,145753,145753,145753,36,134.0,1682.0,16272.0,7377.0,23649.0
541,2020-03-26,NY,37258.0,84846.0,NaN,5327.0,6844.0,1290.0,1290.0,NaN,NaN,NaN,c9e5180c39aab68a5662116651d17a05f4e4b966,2020-03-26T20:00:00Z,385.0,6844.0,122104,122104,122104,36,100.0,3039.0,12178.0,6447.0,18625.0
597,2020-03-25,NY,30811.0,72668.0,NaN,NaN,3805.0,NaN,NaN,NaN,NaN,NaN,332b18596170cd3e35617cfba48a5723aa2ec8f3,2020-03-25T20:00:00Z,285.0,3805.0,103479,103479,103479,36,75.0,571.0,7063.0,5146.0,12209.0
653,2020-03-24,NY,25665.0,65605.0,NaN,NaN,3234.0,NaN,NaN,NaN,NaN,NaN,ea3323c8187b8ff5574d3576f83791e01dd1521f,2020-03-24T20:00:00Z,210.0,3234.0,91270,91270,91270,36,96.0,599.0,8191.0,4790.0,12981.0
709,2020-03-23,NY,20875.0,57414.0,NaN,NaN,2635.0,NaN,NaN,NaN,NaN,NaN,40440cdc2bc6ecd1d88040f01ebbdcb130a33257,2020-03-23T20:00:00Z,114.0,2635.0,78289,78289,78289,36,0.0,661.0,11181.0,5707.0,16888.0
765,2020-03-22,NY,15168.0,46233.0,NaN,NaN,1974.0,NaN,NaN,NaN,NaN,NaN,0df3f76e6407f511b0c5bf4f5647cce8f407250e,2020-03-22T20:00:00Z,114.0,1974.0,61401,61401,61401,36,70.0,371.0,11152.0,4812.0,15964.0
821,2020-03-21,NY,10356.0,35081.0,NaN,NaN,1603.0,NaN,NaN,NaN,NaN,NaN,eb983c3fb4fc2d7f3c2c1250578379f502787c29,2020-03-21T20:00:00Z,44.0,1603.0,45437,45437,45437,36,9.0,1603.0,9756.0,3254.0,13010.0
877,2020-03-20,NY,7102.0,25325.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5293b5c5920709d4f3cf66b901621a61a47d0d23,2020-03-20T20:00:00Z,35.0,NaN,32427,32427,32427,36,23.0,0.0,7193.0,2950.0,10143.0
933,2020-03-19,NY,4152.0,18132.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2eabc9b73139066e3613021b1e9c9deaf8af733c,2020-03-19T20:00:00Z,12.0,NaN,22284,22284,22284,36,0.0,0.0,5917.0,1770.0,7687.0
989,2020-03-18,NY,2382.0,12215.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65a08e6a0f81bd2c4bbc9988a17f0892d2ec4d35,2020-03-18T20:00:00Z,12.0,NaN,14597,14597,14597,36,5.0,0.0,6709.0,682.0,7391.0
1045,2020-03-17,NY,1700.0,5506.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a2d96e7a962926fa3165aef038360c097b6be4ce,2020-03-17T20:00:00Z,7.0,NaN,7206,7206,7206,36,0.0,0.0,963.0,750.0,1713.0
1101,2020-03-16,NY,950.0,4543.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,994a65ba75be3681f76ff4612eb8fde85cff81cd,2020-03-16T20:00:00Z,7.0,NaN,5493,5493,5493,36,4.0,0.0,0.0,221.0,221.0
1154,2020-03-15,NY,729.0,4543.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,963f632b5d1577cd5cf9b6c332a912c2fdebea16,2020-03-15T20:00:00Z,3.0,NaN,5272,5272,5272,36,3.0,0.0,1764.0,205.0,1969.0
1205,2020-03-14,NY,524.0,2779.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f28c39ca671c26d022ff2556494ad8767765eb93,2020-03-14T20:00:00Z,NaN,NaN,3303,3303,3303,36,0.0,0.0,0.0,103.0,103.0
1256,2020-03-13,NY,421.0,2779.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a0a0e2997c411014ef2cd98b9502387730f585c7,2020-03-13T20:00:00Z,NaN,NaN,3200,3200,3200,36,0.0,0.0,2687.0,205.0,2892.0
1307,2020-03-12,NY,216.0,92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78ea2217b81c0eba25ec04b1196199ad81793ead,2020-03-12T20:00:00Z,NaN,NaN,308,308,308,36,0.0,0.0,0.0,0.0,0.0
1358,2020-03-11,NY,216.0,92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6fbded3854324c39522ab7fdb01d2087f60e2d2b,2020-03-11T20:00:00Z,NaN,NaN,308,308,308,36,0.0,0.0,0.0,43.0,43.0
1409,2020-03-10,NY,173.0,92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,193f85893cecb99d063a03060bc4802d2d6458f1,2020-03-10T20:00:00Z,NaN,NaN,265,265,265,36,0.0,0.0,0.0,31.0,31.0
1460,2020-03-09,NY,142.0,92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,260a070d28ed40a35e8b31aca5f4ab3352dc9ba8,2020-03-09T20:00:00Z,NaN,NaN,234,234,234,36,0.0,0.0,0.0,37.0,37.0
1511,2020-03-08,NY,105.0,92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f6d3b78f41cadeaf08e72f35692a9619d70aad07,2020-03-08T20:00:00Z,NaN,NaN,197,197,197,36,0.0,0.0,0.0,29.0,29.0
1562,2020-03-07,NY,76.0,92.0,236.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53a82f90b4d4a28a5b06248b1e4c78e9229312dd,2020-03-07T21:00:00Z,NaN,NaN,404,168,168,36,0.0,0.0,0.0,43.0,43.0
1603,2020-03-06,NY,33.0,92.0,236.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18e7306085561597629e7ffac110572b1aa9f9e5,2020-03-06T21:00:00Z,NaN,NaN,361,125,125,36,0.0,0.0,16.0,11.0,27.0
1630,2020-03-05,NY,22.0,76.0,24.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a5eb1a3c895ee3acd8c87b19363bab6d581b3933,2020-03-05T21:00:00Z,NaN,NaN,122,98,98,36,0.0,0.0,28.0,16.0,44.0
1647,2020-03-04,NY,6.0,48.0,24.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0e095e2b3db515b00d892276e6cac6912b1e0111,2020-03-04T21:00:00Z,NaN,NaN,78,54,54,36,NaN,NaN,NaN,NaN,NaN

In [62]:
df['pos_test_percentage'] = df['positive']/df["total"]

In [63]:
df

,date,state,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,onVentilatorCumulative,recovered,hash,dateChecked,death,hospitalized,total,totalTestResults,posNeg,fips,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease,pos_test_percentage
0,2020-04-04,AK,171.0,5869.0,NaN,NaN,16.0,NaN,NaN,NaN,NaN,NaN,10a0cf7d2d88dce27674dda730950a2661caa4b0,2020-04-04T20:00:00Z,5.0,16.0,6040,6040,6040,2,2.0,1.0,10.0,14.0,24.0,0.028311
1,2020-04-04,AL,1580.0,9273.0,NaN,NaN,212.0,NaN,NaN,NaN,NaN,NaN,963802ea3a71c8b5d74fec7b17f1fb98e9547168,2020-04-04T20:00:00Z,43.0,212.0,10853,10853,10853,1,8.0,212.0,1086.0,148.0,1234.0,0.145582
2,2020-04-04,AR,743.0,9627.0,NaN,72.0,NaN,NaN,NaN,23.0,NaN,79.0,b8737741e743a45a91088157640ca1a0b49adc9d,2020-04-04T20:00:00Z,14.0,NaN,10370,10370,10370,5,2.0,0.0,632.0,39.0,671.0,0.071649
3,2020-04-04,AS,NaN,20.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a7a8c57370e5f59f49e7b95394059c629156c29d,2020-04-04T20:00:00Z,0.0,NaN,26,20,20,60,0.0,0.0,0.0,0.0,0.0,NaN
4,2020-04-04,AZ,2019.0,25141.0,NaN,NaN,297.0,NaN,104.0,NaN,NaN,NaN,cfb482b3a35b4fc17924cec3a44f93a4ca0644ad,2020-04-04T20:00:00Z,52.0,297.0,27160,27160,27160,4,11.0,48.0,2237.0,250.0,2487.0,0.074337
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1648,2020-03-04,OR,3.0,29.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d63f4cf486a6d2f86062b9af1bd46955abd90cb9,2020-03-04T21:00:00Z,NaN,NaN,50,32,32,41,NaN,NaN,NaN,NaN,NaN,0.060000
1649,2020-03-04,SC,0.0,5.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,012fa30a9958580f589eb7d1de5e5a81c327b1a5,2020-03-04T21:00:00Z,NaN,NaN,5,5,5,45,NaN,NaN,NaN,NaN,NaN,0.000000
1650,2020-03-04,TX,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d29839e81cae6ba53df2d1a1d7bfeddfd4fc8509,2020-03-04T21:00:00Z,NaN,NaN,1,1,1,48,NaN,NaN,NaN,NaN,NaN,1.000000
1651,2020-03-04,WA,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,e07bd12171fed21351784c462b0dab23d8cfabbd,2020-03-04T21:00:00Z,10.0,NaN,39,39,39,53,NaN,NaN,NaN,NaN,NaN,1.000000
1652,2020-03-04,WI,1.0,19.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,c1fede94be9a426dc9c3b5d26d33b9f168fec21c,2020-03-04T21:00:00Z,NaN,NaN,26,20,20,55,NaN,NaN,NaN,NaN,NaN,0.038462

In [56]:
df["dateChecked"]

0       2020-04-04T20:00:00Z
1       2020-04-04T20:00:00Z
2       2020-04-04T20:00:00Z
3       2020-04-04T20:00:00Z
4       2020-04-04T20:00:00Z
                ...
1648    2020-03-04T21:00:00Z
1649    2020-03-04T21:00:00Z
1650    2020-03-04T21:00:00Z
1651    2020-03-04T21:00:00Z
1652    2020-03-04T21:00:00Z
Name: dateChecked, Length: 1653, dtype: object

In [34]:
s = deepcopy(df["date"][0])

In [36]:
s

20200404

In [39]:
s

20200404

In [38]:
date= datetime(year = (s[0:4]), month = (s[4:6]), day = (s[6:8]))

IndexError: invalid index to scalar variable.

## County Data

In [64]:
ls

COVID.DATA.LIC.AGMT.pdf        custom_license/
README.md                      json_schema.txt
biorxiv_medrxiv/               metadata.csv
comm_use_subset/               metadata.readme
county_date/                   noncomm_use_subset/
covid19_workbook.ipynb         states-daily.csv
covid_19_visualizations.ipynb

In [65]:
cd county_date/

/Users/johnrick/Desktop/DataScienceLearn/blog_covid19/county_date

In [67]:
cd covid-19-data/

/Users/johnrick/Desktop/DataScienceLearn/blog_covid19/county_date/covid-19-data

In [68]:
ls

LICENSE          README.md        us-counties.csv  us-states.csv

In [70]:
county = pd.read_csv("us-counties.csv")

In [75]:
ny = county[county['state'] == "New York"]

In [82]:
ny.head()

           date         county     state     fips  cases  deaths
416  2020-03-01  New York City  New York      NaN      1       0
448  2020-03-02  New York City  New York      NaN      1       0
482  2020-03-03  New York City  New York      NaN      2       0
518  2020-03-04  New York City  New York      NaN      2       0
519  2020-03-04    Westchester  New York  36119.0      9       0

In [83]:
ny

             date         county     state     fips  cases  deaths
416    2020-03-01  New York City  New York      NaN      1       0
448    2020-03-02  New York City  New York      NaN      1       0
482    2020-03-03  New York City  New York      NaN      2       0
518    2020-03-04  New York City  New York      NaN      2       0
519    2020-03-04    Westchester  New York  36119.0      9       0
...           ...            ...       ...      ...    ...     ...
32296  2020-04-04     Washington  New York  36115.0     17       1
32297  2020-04-04          Wayne  New York  36117.0     30       0
32298  2020-04-04    Westchester  New York  36119.0  13080     197
32299  2020-04-04        Wyoming  New York  36121.0     18       1
32300  2020-04-04          Yates  New York  36123.0      2       0

[1086 rows x 6 columns]